spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 32862961756-n64lj4vhmhbr0bqq8gmqqcqivjvmp7q0.apps.googleusercontent.com
            client-secret: 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
            redirectUri: http://localhost:8080/login/oauth2/code/google
          facebook:
            clientId: 2680580905440496
            clientSecret: 4e54e0ac29c6d11985ef24bf451ebc45
            scope:
              - email
              - public_profile

